### PR TITLE
Added an exercise explaining destructuring

### PR DESCRIPTION
**Pull request by zbicin**

### CODE REVIEW

**Comment by domenic** [comment]
This seems great! However, I don't have time to maintain this workshopper anymore. Would you be interested in being added as a maintainer, so you can merge and publish this yourself?

**Comment by zbicin** [comment]
Sure thing, I'm in :)

**Comment by domenic** [comment]
Great! I've invited you as a collaborator to the GitHub repo, and if you'll let me know your npm username, I can add you as an owner there too!

**Comment by zbicin** [comment]
It's the same as in GitHub: [zbicin](https://www.npmjs.com/~zbicin).

**Pull request merged**
